name: Keep Streamlit App Awake

on:
  schedule:
    # Running every 4 hours is safer than 10. 
    # If the app sleeps, it takes time to wake up.
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run_selenium_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Wake Up Script
        run: python keep_alive.py
